### PR TITLE
Enabled basic auth

### PR DESCRIPTION
**Pull request by bmavity**
This pull request includes basic auth, and does not affect the way token auth already works.

Is a possible solution for #34

### CODE REVIEW

**Comment by domschiener** [comment]
Could you update this PR to the latest changes made to the iota.js file?

**Comment by bmavity** [comment]
I rebased the commit on top of master, but I can't seem to successfully build the distribution due to a security error in guld-nsp. Were you able to get it to build?

**Comment by HerrMuellerluedenscheid** [comment]
Hey, are there any news on this PR? Conflicts resolved or should we have a look?

**Comment by obany** [comment]
Closing as these changes are on an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.

**Pull request closed without merging**
